### ISSUE TITLE
More question then issue but ..

### ISSUE THREAD

**Issue by Paku-** [p-j/meteor-gravatar#10]
Does this issue impact your code ?

[email-normalize >> conflict with Meteor email package #4](https://github.com/iDoRecall/email-normalize/issues/4)

We had to remove the "email-normalize" to make emails working. The question is if  your module works without it ?

**Comment by p-j** [comment]
Only if you calculate the MD5 yourself beforehand.
[Using the email will call the email-normalize module](https://github.com/p-j/meteor-gravatar/blob/master/gravatar.js#L62)

**Comment by p-j** [comment]
So the workaround currently is to calculate the MD5 beforehand.
I'll probably remove the `email-normalize` dependency in the future or hide it behind a flag. This way, the decision to normalize the email address or not belongs to the developer.
It also means that it is the responsibility of the developer to check whether the `email-normalize` plugin is fixed or not.

Thanks for the heads up. I should publish a fix by the end of the week and close this issue at the same time.
