### ISSUE TITLE
GET error

### ISSUE THREAD

**Issue by cdcv** [p-j/meteor-gravatar#11]
In the console log of our meteor app, we repeatedly get the following error:
GET https://secure.gravatar.com/avatar/00000000000000000000000000000000?default=404&size=200 404 ()
We can't figure out what code within the app is even trying to user gravatar, what dependency is leading to it, or how to get rid of it.
Is there a way to prevent this?

Thanks

**Comment by p-j** [comment]
You can get [here](https://atmospherejs.com/jparker/gravatar) a list of package depending on mine.

Without more information on your app there is little I can do.
