### ISSUE TITLE
Gravatar 404

### ISSUE THREAD

**Issue by carlosalvidrez** [p-j/meteor-gravatar#14]
Hi, thank you for making this package!
I am getting a 404, wondering if you may have any hints on a typical cause... 

GET https://secure.gravatar.com/avatar/00000000000000000000000000000000?default=404&size=200 404

Thanks

**Comment by p-j** [comment]
Hi @carlosalvidrez 
Would you mind sharing a piece of code that would reproduce the error?

**Comment by p-j** [comment]
I'm going to close this, feel free to reopen if you have a sample of code to reproduce the issue and I'll take a look.
