### ISSUE TITLE
Consider normalizing the email address for Gravatar

### ISSUE THREAD

**Issue by dandv** [p-j/meteor-gravatar#2]
If the user registers with a [sub-address](https://en.wikipedia.org/wiki/Email_address#Sub-addressing) (e.g. `joe+yourapp@gmail.com`), Gravatar isn't smart enough to find the picture of `joe@gmail.com`.

We've just released a package to correct for that, [`idorecall:email-normalize`](https://github.com/iDoRecall/email-normalize). I can proudly say that it's [the _best_ solution](https://github.com/iDoRecall/email-normalize#prior-art) I've seen so far for this problem, as it supports not just Gmail, but any domain hosted with Google Apps for Work (via an MX DNS lookup), plus FastMail, Microsoft, Yahoo! and others.

**Comment by p-j** [comment]
Thanks for the pointer @dandv.

I'll certainly integrate that, it's an inconvenience I've had to deal with myself and the solution is elegant.
I'll have to test for the original email before though as the user may want to use separate Gravatar for two sub-address.

**Comment by dandv** [comment]
Correct - made a [note](https://github.com/iDoRecall/email-normalize#notes) about that.

**Comment by p-j** [comment]
Actually, a clever way of doing it could be to ask for the gravatar with the sub-address and use the [`d`](https://en.gravatar.com/site/implement/images/#default-image) parameter with the standard address.
That being a default setting that the package user can override if he wanted.

What do you think ?

**Comment by dandv** [comment]
That looks like a nifty idea, esp. if the pass through the user's `d` to the very end:

<img src="//www.gravatar.com/avatar/hash-of-user-supplied-email?d=http%3A%2F%2Fgravatar.com%2Favatar%2hash-of-normalize-email%3Fd%3D..." />

**Comment by p-j** [comment]
I've integrated this feature in this commit https://github.com/p-j/meteor-gravatar/commit/faec93b2a0c654e76506a07c15be9d801363632a 

Thanks for your help !
