### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by neurosoup** [p-j/meteor-gravatar#3]
Hello,

api.use('jparker:gravatar') inside my package leads to this error : 

"ReferenceError: _ is not defined
at Object.Gravatar.imageUrl (packages/jparker:gravatar/gravatar.js:67:1)"

I think you must add a reference to 'underscore' inside your package.js

Thanks

**Comment by p-j** [comment]
It's absolutely true.
I need to fix that.

Thanks for reporting that.

**Comment by neurosoup** [comment]
Thanks for the fix and thank you for the package too !

De : Jérémie Parker [mailto:notifications@github.com] 
Envoyé : mardi 11 août 2015 23:16
À : p-j/meteor-gravatar
Cc : neurosoup
Objet : Re: [meteor-gravatar] ReferenceError: _ is not defined (#3)

It's absolutely true.
I need to fix that.

Thanks for reporting that.

**Comment by neurosoup** [comment]
Thanks for the fix and thank you for the package too !

**Comment by p-j** [comment]
It is fixed by https://github.com/p-j/meteor-gravatar/commit/d8b80550bae630c42eae55e3dbaaf5e03495a434

Thanks for your help !
