### ISSUE TITLE
Bug with version 0.4.0 - Email normalize

### ISSUE THREAD

**Issue by kristijanhusak** [p-j/meteor-gravatar#5]
Hi, I just did a meteor update, and got latest version 0.4.0. When i started the application, bunch of errors appear in the console. Here's just those that are needed for this issue:

```
Uncaught ReferenceError: Npm is not defined(anonymous function) @ email.js:3(anonymous function) @ idorecall_email-normalize.js?0cdb1600384f7108f43241d583bfd515371c7793:162(anonymous function) @ idorecall_email-normalize.js?0cdb1600384f7108f43241d583bfd515371c7793:171
jparker_gravatar.js?9216ad22993072a2ae1047bafd79331ba218ff32:23 Uncaught TypeError: Cannot read property 'Email' of undefined(anonymous function) @ jparker_gravatar.js?9216ad22993072a2ae1047bafd79331ba218ff32:23(anonymous function) @ jparker_gravatar.js?9216ad22993072a2ae1047bafd79331ba218ff32:132
global-imports.js?d5b0c5ebbca327dd5d5a50d5a9902dc6ad7d4b2f:5 Uncaught TypeError: Cannot read property 'Gravatar' of undefined
```

When I downgraded back to 0.3.1, everything works fine.

**Comment by p-j** [comment]
When I ran the tests I had the same errors but it worked fine anyway.
Anyway, the error is from [idorecall:email-normalize](https://github.com/iDoRecall/email-normalize/blob/240f9a749a7bb6322e27c33e1047cb5bd0aa6130/email.js#L3) 
It seems it lacks a `Npm.depends` declaration in its [package.js](https://github.com/iDoRecall/email-normalize/blob/240f9a749a7bb6322e27c33e1047cb5bd0aa6130/package.js)

**Comment by kristijanhusak** [comment]
Yeah, i know. Should I open issue there, or you will do that?

**Comment by p-j** [comment]
I'm in the middle of writing it but you can go ahead if you want ;)

**Comment by kristijanhusak** [comment]
I'll leave it to you, you are using it as depencency :)

**Comment by p-j** [comment]
Should be fixed now.
Thanks for reporting !

**Comment by kristijanhusak** [comment]
It's working, thanks!
